Repository WooRibound/WooRibound-API, pull requests merged in 2024-11, with the labels that each got.

#13 Feature/#4 entity hw
  build.gradle
  src/main/java/com/wooribound/domain/admin/entity/Admin.java
  src/main/java/com/wooribound/domain/corporate/entity/Enterprise.java
  src/main/java/com/wooribound/domain/corporate/entity/enterprise.java
  src/main/java/com/wooribound/domain/education/entity/Education.java
  src/main/java/com/wooribound/domain/education/entity/education.java
  src/main/java/com/wooribound/domain/individual/entity/InterestJob.java
  src/main/java/com/wooribound/domain/individual/entity/Resume.java
  src/main/java/com/wooribound/domain/individual/entity/WbUser.java
  src/main/java/com/wooribound/domain/individual/entity/WorkHistory.java
  src/main/java/com/wooribound/domain/individual/entity/interestJobs.java
  src/main/java/com/wooribound/domain/individual/entity/resume.java
  src/main/java/com/wooribound/domain/individual/entity/wbUser.java
  src/main/java/com/wooribound/domain/individual/entity/workHistory.java
  src/main/java/com/wooribound/domain/recruitment/entity/JobPosting.java
  src/main/java/com/wooribound/domain/recruitment/entity/jobPostings.java
  src/main/java/com/wooribound/domain/recruitment/entity/jobs.java
  src/main/java/com/wooribound/global/entity/Employment.java
  src/main/java/com/wooribound/global/entity/Job.java
  src/main/java/com/wooribound/global/entity/Notification.java
  src/main/java/com/wooribound/global/entity/UserApply.java
  src/main/java/com/wooribound/global/entity/UserEdu.java
  src/main/resources/application.properties
Labels: enhancement

#12 Feature/#4 entity jw
  src/main/java/com/wooribound/domain/individual/entity/InterestJob.java
  src/main/java/com/wooribound/domain/individual/entity/WorkHistory.java
  src/main/java/com/wooribound/domain/recruitment/entity/JobPosting.java
  src/main/java/com/wooribound/global/entity/Employment.java
  src/main/java/com/wooribound/global/entity/Notification.java
  src/main/java/com/wooribound/global/entity/UserApply.java
  src/main/java/com/wooribound/global/entity/UserEdu.java
Labels: enhancement

#15 Feature/#4 entity sh1
  src/main/java/com/wooribound/domain/individual/entity/Resume.java
  src/main/java/com/wooribound/domain/individual/entity/WbUser.java
  src/main/java/com/wooribound/domain/individual/entity/WorkHistory.java
  src/main/java/com/wooribound/global/entity/Job.java
Labels: enhancement

#19 data.sql 작성 및 AdminEducation controller 추가
  src/main/java/com/wooribound/domain/admin/controller/AdminEduactionController.java
  src/main/java/com/wooribound/domain/individual/entity/Resume.java
  src/main/java/com/wooribound/domain/individual/entity/WbUser.java
  src/main/resources/data.sql
Labels: enhancement

#21 [feat] #4 - naver 제공 정보를 사용하기 위하여 entity 수정 및 기업 매출 컬럼 정수형 수정
  src/main/java/com/wooribound/domain/corporate/entity/Enterprise.java
  src/main/java/com/wooribound/domain/individual/entity/Resume.java
  src/main/java/com/wooribound/domain/individual/entity/WbUser.java
Labels: enhancement

#28 feat : #27 knowhow entity 생성 및 교육 관련 파일 삭제
  src/main/java/com/wooribound/api/individual/controller/WbUserKnowhowController.java
  src/main/java/com/wooribound/domain/education/Education.java
  src/main/java/com/wooribound/domain/education/EducationRepository.java
  src/main/java/com/wooribound/domain/knowhow/Knowhow.java
  src/main/java/com/wooribound/domain/knowhow/KnowhowRepository.java
  src/main/java/com/wooribound/domain/knowhow/dto/KnowhowDTO.java
  src/main/java/com/wooribound/domain/useredu/UserEdu.java
  src/main/java/com/wooribound/domain/useredu/UserEduRepository.java
  src/main/java/com/wooribound/domain/wbuser/WbUser.java
  src/main/resources/data.sql
Labels: enhancement

#29 일반 유저 naver OAuth 구현
  src/main/java/com/wooribound/domain/wbuser/WbUser.java
  src/main/java/com/wooribound/global/config/Redisconfig.java
  src/main/java/com/wooribound/global/config/SwaggerConfig.java
  src/main/java/com/wooribound/global/security/AuthController.java
  src/main/java/com/wooribound/global/security/JWTFilter.java
  src/main/java/com/wooribound/global/security/OauthResponseDTO/NaverResponse.java
  src/main/java/com/wooribound/global/security/OauthResponseDTO/OAuth2Response.java
  src/main/java/com/wooribound/global/security/OauthResponseDTO/RefreshTokenRequest.java
  src/main/java/com/wooribound/global/security/OauthTestController.java
  src/main/java/com/wooribound/global/security/SecurityConfig.java
  src/main/java/com/wooribound/global/security/controller/AuthController.java
  src/main/java/com/wooribound/global/security/successhandler/WbUserSuccessHandler.java
  src/main/java/com/wooribound/global/security/userdetail/wbuser/WbUserDetail.java
  src/main/java/com/wooribound/global/security/userdetail/wbuser/WbUserDetailService.java
  src/main/java/com/wooribound/global/util/JWTUtil.java
  src/main/resources/static/oauth.html
Labels: enhancement

#31 feat : #30 전체 직무 조회
  src/main/java/com/wooribound/domain/job/JobDTO.java
  src/main/java/com/wooribound/domain/job/JobService.java
  src/main/java/com/wooribound/domain/job/JobServiceImpl.java
  src/main/java/com/wooribound/global/controller/GlobalController.java
Labels: enhancement

#32 Feature/#26 user apply merge
  src/main/java/com/wooribound/api/individual/controller/WbUserAuthController.java
  src/main/java/com/wooribound/api/individual/controller/WbUserInfoController.java
  src/main/java/com/wooribound/api/individual/controller/WbUserJobPostingController.java
  src/main/java/com/wooribound/api/individual/dto/UserApplyDTO.java
  src/main/java/com/wooribound/api/individual/dto/UserJobPostingDTO.java
  src/main/java/com/wooribound/api/individual/facade/WbUserInfoFacade.java
  src/main/java/com/wooribound/api/individual/facade/WbUserJobPostingFacade.java
  src/main/java/com/wooribound/domain/employment/EmploymentRepository.java
  src/main/java/com/wooribound/domain/jobposting/DTO/WbUserJobPostingDTO.java
  src/main/java/com/wooribound/domain/jobposting/DTO/WbUserJobPostingDetailDTO.java
  src/main/java/com/wooribound/domain/jobposting/JobPostingRepository.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/userapply/DTO/WbUserApplyDTO.java
  src/main/java/com/wooribound/domain/userapply/Service/UserApplyService.java
  src/main/java/com/wooribound/domain/userapply/Service/UserApplyServiceImpl.java
  src/main/java/com/wooribound/domain/userapply/UserApplyRepository.java
Labels: enhancement

#37 Feature/#26 user apply refactoring
  .gitignore
  src/main/java/com/wooribound/api/individual/controller/WbUserInfoController.java
  src/main/java/com/wooribound/api/individual/controller/WbUserJobPostingController.java
  src/main/java/com/wooribound/api/individual/dto/UserJobPostingDTO.java
  src/main/java/com/wooribound/api/individual/facade/WbUserInfoFacade.java
  src/main/java/com/wooribound/api/individual/facade/WbUserJobPostingFacade.java
  src/main/java/com/wooribound/domain/userapply/Service/UserApplyService.java
  src/main/java/com/wooribound/domain/userapply/Service/UserApplyServiceImpl.java
Labels: enhancement

#38 [chore] #36 - .sql job테이블 insert문 추가
  src/main/resources/data.sql
Labels: enhancement

#42 [feat] #35 - 노하우 삭제 및 예외처리 수정
  src/main/java/com/wooribound/api/admin/controller/AdminKnowhowController.java
  src/main/java/com/wooribound/api/admin/dto/AdminKnowhowDTO.java
  src/main/java/com/wooribound/api/admin/facade/AdminKnowhowFacade.java
  src/main/java/com/wooribound/domain/knowhow/KnowhowRepository.java
  src/main/java/com/wooribound/domain/knowhow/KnowhowService.java
  src/main/java/com/wooribound/domain/knowhow/KnowhowServiceImpl.java
  src/main/java/com/wooribound/global/exception/NoKnowhowException.java
Labels: enhancement

#43 [fix] #39 - CORS 오류 수정(로컬 개발 환경에서만 허용하도록 변경)
  src/main/java/com/wooribound/global/security/SecurityConfig.java
Labels: wontfix

#46 Feature/#35 admin jobposting
  src/main/java/com/wooribound/api/admin/controller/AdminJobPostingController.java
  src/main/java/com/wooribound/api/admin/controller/AdminKnowhowController.java
  src/main/java/com/wooribound/api/admin/dto/AdminJobPostingReqDTO.java
  src/main/java/com/wooribound/api/admin/dto/AdminJoinDTO.java
  src/main/java/com/wooribound/api/admin/dto/AdminKnowhowReqDTO.java
  src/main/java/com/wooribound/api/admin/facade/AdminJobPostingFacade.java
  src/main/java/com/wooribound/api/admin/facade/AdminKnowhowFacade.java
  src/main/java/com/wooribound/api/individual/controller/WbUserJobPostingController.java
  src/main/java/com/wooribound/api/individual/facade/WbUserJobPostingFacade.java
  src/main/java/com/wooribound/domain/jobposting/DTO/JobPostingDTO.java
  src/main/java/com/wooribound/domain/jobposting/DTO/JobPostingDetailDTO.java
  src/main/java/com/wooribound/domain/jobposting/JobPostingRepository.java
  src/main/java/com/wooribound/domain/jobposting/Service/AdminJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/AdminJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/knowhow/service/AdminKnowhowService.java
  src/main/java/com/wooribound/domain/knowhow/service/AdminKnowhowServiceImpl.java
  src/main/java/com/wooribound/global/exception/NoJobPostingException.java
  src/main/java/com/wooribound/global/handler/GlobalExceptionHandler.java
Labels: enhancement

#48 Feature/#20 auth
  src/main/java/com/wooribound/api/admin/controller/AdminAuthController.java
  src/main/java/com/wooribound/api/admin/facade/AdminAuthFacade.java
  src/main/java/com/wooribound/api/corporate/controller/EnterpriseAuthController.java
  src/main/java/com/wooribound/api/corporate/facade/EnterpriseAuthFacade.java
  src/main/java/com/wooribound/api/individual/controller/WbUserAuthController.java
  src/main/java/com/wooribound/api/individual/dto/OAuthDTO.java
  src/main/java/com/wooribound/api/individual/facade/WbUserAuthFacade.java
  src/main/java/com/wooribound/domain/wbuser/WbUser.java
  src/main/java/com/wooribound/global/security/CustomAuthenticationFilter.java
  src/main/java/com/wooribound/global/security/JWTFilter.java
  src/main/java/com/wooribound/global/security/SecurityConfig.java
  src/main/java/com/wooribound/global/security/controller/AuthController.java
  src/main/java/com/wooribound/global/security/successhandler/AdminSuccessHandler.java
  src/main/java/com/wooribound/global/security/successhandler/EnterpriseSuccessHandler.java
  src/main/java/com/wooribound/global/security/successhandler/WbUserSuccessHandler.java
  src/main/java/com/wooribound/global/security/userdetail/wbuser/WbUserDetail.java
  src/main/java/com/wooribound/global/security/userdetail/wbuser/WbUserDetailService.java
  src/main/java/com/wooribound/global/util/JWTUtil.java
Labels: enhancement

#49 Feature/#35 admin enterprise manage
  src/main/java/com/wooribound/api/admin/controller/AdminAuthController.java
  src/main/java/com/wooribound/api/admin/dto/AdminApproveReqDTO.java
  src/main/java/com/wooribound/api/admin/facade/AdminAuthFacade.java
  src/main/java/com/wooribound/domain/admin/AdminService.java
  src/main/java/com/wooribound/domain/admin/AdminServiceImpl.java
  src/main/java/com/wooribound/domain/enterprise/EnterpriseRepository.java
Labels: enhancement

#50 [fix] #35 - AdminAuthFacade 충돌 부분 해결
  src/main/java/com/wooribound/api/admin/facade/AdminAuthFacade.java
Labels: enhancement

#51 [feat] #33 - 우바 점수 조회 기능 추가
  src/main/java/com/wooribound/api/individual/controller/WbUserInfoController.java
  src/main/java/com/wooribound/api/individual/facade/WbUserInfoFacade.java
  src/main/java/com/wooribound/domain/wbuser/WbUserService.java
  src/main/java/com/wooribound/domain/wbuser/WbUserServiceImpl.java
Labels: enhancement

#52 회원가입 기능 개발, 타임존 설정
  src/main/java/com/wooribound/WooriboundApplication.java
  src/main/java/com/wooribound/api/admin/facade/AdminAuthFacade.java
  src/main/java/com/wooribound/api/individual/controller/WbUserAuthController.java
  src/main/java/com/wooribound/api/individual/dto/WbUserJoinInfoResponseDTO.java
  src/main/java/com/wooribound/api/individual/facade/WbUserAuthFacade.java
  src/main/java/com/wooribound/domain/wbuser/WbUserService.java
  src/main/java/com/wooribound/domain/wbuser/WbUserServiceImpl.java
  src/main/java/com/wooribound/global/exception/AuthenticationException.java
  src/main/java/com/wooribound/global/handler/GlobalExceptionHandler.java
  src/main/java/com/wooribound/global/security/userdetail/wbuser/WbUserDetailService.java
  src/main/java/com/wooribound/global/util/AuthenticateUtil.java
  src/main/resources/application.properties
Labels: enhancement

#57 [feat] #34 - enterprise 지원자 결과 설정 기능 구현
  src/main/java/com/wooribound/api/corporate/controller/EnterpriseJobPostingController.java
  src/main/java/com/wooribound/api/corporate/facade/EnterpriseJobPostingFacade.java
  src/main/java/com/wooribound/api/individual/controller/WbUserInfoController.java
  src/main/java/com/wooribound/api/individual/facade/WbUserInfoFacade.java
  src/main/java/com/wooribound/domain/enterprise/EnterpriseRepository.java
  src/main/java/com/wooribound/domain/jobposting/Service/EntJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/EntJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/userapply/Service/UserApplyService.java
  src/main/java/com/wooribound/domain/userapply/Service/UserApplyServiceImpl.java
  src/main/java/com/wooribound/domain/userapply/UserApplyRepository.java
  src/main/java/com/wooribound/domain/userapply/dto/ApplicantResultReqDTO.java
  src/main/java/com/wooribound/domain/userapply/dto/WbUserApplyDTO.java
Labels: enhancement

#58 Feature/#35 admin individual
  src/main/java/com/wooribound/api/admin/controller/AdminIndividualController.java
  src/main/java/com/wooribound/api/admin/dto/AdminWbUserReqDTO.java
  src/main/java/com/wooribound/api/admin/facade/AdminIndividualFacade.java
  src/main/java/com/wooribound/domain/job/JobDTO.java
  src/main/java/com/wooribound/domain/resume/ResumeService.java
  src/main/java/com/wooribound/domain/resume/ResumeServiceImpl.java
  src/main/java/com/wooribound/domain/resume/dto/ResumeDetailDTO.java
  src/main/java/com/wooribound/domain/wbuser/AdminWbUserService.java
  src/main/java/com/wooribound/domain/wbuser/AdminWbUserServiceImpl.java
  src/main/java/com/wooribound/domain/wbuser/WbUserRepository.java
  src/main/java/com/wooribound/domain/wbuser/dto/AdminIndividualDTO.java
  src/main/java/com/wooribound/domain/workhistory/WorkHistory.java
  src/main/java/com/wooribound/domain/workhistory/WorkHistoryRepository.java
Labels: enhancement

#59 Feature/#35 admin enterprise
  src/main/java/com/wooribound/api/admin/controller/AdminEnterpriseController.java
  src/main/java/com/wooribound/api/admin/dto/AdminEnterpriseReqDTO.java
  src/main/java/com/wooribound/api/admin/facade/AdminEnterpriseFacade.java
  src/main/java/com/wooribound/api/admin/facade/AdminIndividualFacade.java
  src/main/java/com/wooribound/domain/enterprise/EnterpriseRepository.java
  src/main/java/com/wooribound/domain/enterprise/dto/AdminEnterpriseDTO.java
  src/main/java/com/wooribound/domain/enterprise/dto/AdminEnterpriseDetailDTO.java
  src/main/java/com/wooribound/domain/enterprise/service/AdminEnterpriseService.java
  src/main/java/com/wooribound/domain/enterprise/service/AdminEnterpriseServiceImpl.java
  src/main/java/com/wooribound/domain/wbuser/WbUserRepository.java
  src/main/java/com/wooribound/domain/wbuser/service/AdminWbUserService.java
  src/main/java/com/wooribound/domain/wbuser/service/AdminWbUserServiceImpl.java
Labels: enhancement

#61 [fix] - jobposting/DTO 패키지명 소문자로 변경
  src/main/java/com/wooribound/api/admin/controller/AdminJobPostingController.java
  src/main/java/com/wooribound/api/admin/facade/AdminJobPostingFacade.java
  src/main/java/com/wooribound/api/corporate/controller/EnterpriseJobPostingController.java
  src/main/java/com/wooribound/api/corporate/facade/EnterpriseJobPostingFacade.java
  src/main/java/com/wooribound/api/individual/controller/WbUserJobPostingController.java
  src/main/java/com/wooribound/api/individual/facade/WbUserJobPostingFacade.java
  src/main/java/com/wooribound/domain/jobposting/JobPostingRepository.java
  src/main/java/com/wooribound/domain/jobposting/Service/AdminJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/AdminJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/jobposting/Service/EntJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/EntJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/jobposting/dto/JobPostingDTO.java
  src/main/java/com/wooribound/domain/jobposting/dto/JobPostingDetailDTO.java
  src/main/java/com/wooribound/domain/jobposting/dto/JobPostingDetailProjection.java
Labels: fix

#64 Modify/#63 notify entity
  src/main/java/com/wooribound/domain/notification/Notification.java
  src/main/java/com/wooribound/domain/userapply/UserApply.java
  src/main/java/com/wooribound/domain/wbuser/WbUser.java
Labels: enhancement

#65 Feature/#20 auth
  src/main/java/com/wooribound/api/corporate/facade/EnterpriseAuthFacade.java
  src/main/java/com/wooribound/api/individual/controller/WbUserAuthController.java
  src/main/java/com/wooribound/api/individual/dto/WbUserJoinInfoResDTO.java
  src/main/java/com/wooribound/api/individual/dto/WbUserJoinReqDTO.java
  src/main/java/com/wooribound/api/individual/dto/WbUserUpdateDTO.java
  src/main/java/com/wooribound/api/individual/facade/WbUserAuthFacade.java
  src/main/java/com/wooribound/domain/interestjob/InterestJob.java
  src/main/java/com/wooribound/domain/interestjob/InterestJobRepository.java
  src/main/java/com/wooribound/domain/interestjob/InterestJobService.java
  src/main/java/com/wooribound/domain/interestjob/InterestJobServiceImpl.java
  src/main/java/com/wooribound/domain/job/JobRepository.java
  src/main/java/com/wooribound/domain/job/JobServiceImpl.java
  src/main/java/com/wooribound/domain/wbuser/WbUser.java
  src/main/java/com/wooribound/domain/wbuser/WbUserService.java
  src/main/java/com/wooribound/domain/wbuser/WbUserServiceImpl.java
  src/main/java/com/wooribound/domain/workhistory/WorkHistoryRepository.java
  src/main/java/com/wooribound/domain/workhistory/WorkHistoryService.java
  src/main/java/com/wooribound/domain/workhistory/WorkHistoryServiceImpl.java
  src/main/java/com/wooribound/global/exception/NoJobException.java
  src/main/java/com/wooribound/global/exception/SaveInterestingJobException.java
  src/main/java/com/wooribound/global/exception/SaveWorkHistoryException.java
  src/main/java/com/wooribound/global/exception/UpdateUserInfoException.java
  src/main/java/com/wooribound/global/handler/GlobalExceptionHandler.java
  src/main/java/com/wooribound/global/security/JWTFilter.java
  src/main/java/com/wooribound/global/security/SecurityConfig.java
  src/main/java/com/wooribound/global/security/successhandler/WbUserSuccessHandler.java
  src/main/resources/data.sql
Labels: enhancement

#66 [chore] #63 - 지원현황과 알림 테이블 일대일 관계로 수정
  src/main/java/com/wooribound/domain/jobposting/JobPosting.java
  src/main/java/com/wooribound/domain/notification/Notification.java
  src/main/java/com/wooribound/domain/userapply/UserApply.java
Labels: enhancement

#67 [feat] #35 - 지원공고 삭제 시, 알림 생성
  src/main/java/com/wooribound/domain/jobposting/JobPostingRepository.java
  src/main/java/com/wooribound/domain/jobposting/Service/AdminJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/userapply/UserApplyRepository.java
  src/main/java/com/wooribound/global/exception/NoUserApplyException.java
  src/main/java/com/wooribound/global/handler/GlobalExceptionHandler.java
Labels: enhancement

#69 첫 네이버 로그인 후 회원 가입 기능 완료
  src/main/java/com/wooribound/api/individual/dto/WbUserJoinReqDTO.java
  src/main/java/com/wooribound/api/individual/facade/WbUserAuthFacade.java
  src/main/java/com/wooribound/domain/wbuser/WbUserService.java
  src/main/java/com/wooribound/domain/wbuser/WbUserServiceImpl.java
Labels: enhancement, fix

#70 Feature/#35 admin pending list
  src/main/java/com/wooribound/api/admin/controller/AdminEnterpriseController.java
  src/main/java/com/wooribound/api/admin/facade/AdminEnterpriseFacade.java
  src/main/java/com/wooribound/domain/admin/AdminServiceImpl.java
  src/main/java/com/wooribound/domain/enterprise/Enterprise.java
  src/main/java/com/wooribound/domain/enterprise/EnterpriseRepository.java
  src/main/java/com/wooribound/domain/enterprise/EnterpriseServiceImpl.java
  src/main/java/com/wooribound/domain/enterprise/dto/AdminPendingEnterpriseDTO.java
  src/main/java/com/wooribound/domain/enterprise/service/AdminEnterpriseService.java
  src/main/java/com/wooribound/domain/enterprise/service/AdminEnterpriseServiceImpl.java
  src/main/java/com/wooribound/global/constant/YNP.java
Labels: enhancement, fix

#71 Feature/#35 admin pending list
  src/main/java/com/wooribound/api/admin/controller/AdminEnterpriseController.java
  src/main/java/com/wooribound/api/admin/facade/AdminEnterpriseFacade.java
  src/main/java/com/wooribound/domain/admin/AdminServiceImpl.java
  src/main/java/com/wooribound/domain/enterprise/EnterpriseRepository.java
  src/main/java/com/wooribound/domain/enterprise/dto/AdminPendingEnterpriseDTO.java
  src/main/java/com/wooribound/domain/enterprise/service/AdminEnterpriseService.java
  src/main/java/com/wooribound/domain/enterprise/service/AdminEnterpriseServiceImpl.java
Labels: enhancement

#73 Feature/#68 user info
  src/main/java/com/wooribound/api/individual/controller/WbUserInfoController.java
  src/main/java/com/wooribound/api/individual/controller/WbUserNotificationController.java
  src/main/java/com/wooribound/api/individual/facade/WbUserInfoFacade.java
  src/main/java/com/wooribound/domain/notification/NotificationRepository.java
  src/main/java/com/wooribound/domain/notification/dto/NotificationDTO.java
  src/main/java/com/wooribound/domain/notification/service/NotificationService.java
  src/main/java/com/wooribound/domain/notification/service/NotificationServiceImpl.java
  src/main/resources/data.sql
Labels: enhancement

#75 [feat] #35 -지혜 목록 조회 시, 경고 누적수에 따른 정렬 기능
  src/main/java/com/wooribound/api/admin/controller/AdminKnowhowController.java
  src/main/java/com/wooribound/api/admin/dto/AdminKnowhowReqDTO.java
  src/main/java/com/wooribound/api/admin/facade/AdminKnowhowFacade.java
  src/main/java/com/wooribound/domain/knowhow/Knowhow.java
  src/main/java/com/wooribound/domain/knowhow/KnowhowRepository.java
  src/main/java/com/wooribound/domain/knowhow/dto/AdminKnowhowDTO.java
  src/main/java/com/wooribound/domain/knowhow/dto/AdminKnowhowDetailDTO.java
  src/main/java/com/wooribound/domain/knowhow/dto/AdminKnowhowDetailProjection.java
  src/main/java/com/wooribound/domain/knowhow/dto/AdminKnowhowProjection.java
  src/main/java/com/wooribound/domain/knowhow/service/AdminKnowhowService.java
  src/main/java/com/wooribound/domain/knowhow/service/AdminKnowhowServiceImpl.java
  src/main/java/com/wooribound/domain/knowhowreported/KnowhowReported.java
  src/main/java/com/wooribound/domain/knowhowreported/KnowhowReportedRepository.java
  src/main/java/com/wooribound/domain/wbuser/WbUser.java
Labels: enhancement

#76 회원탈퇴 기능
  src/main/java/com/wooribound/api/individual/controller/WbUserAuthController.java
  src/main/java/com/wooribound/api/individual/dto/WbUserJoinDTO.java
  src/main/java/com/wooribound/api/individual/facade/WbUserAuthFacade.java
  src/main/java/com/wooribound/domain/wbuser/WbUserService.java
  src/main/java/com/wooribound/domain/wbuser/WbUserServiceImpl.java
  src/main/java/com/wooribound/global/exception/DeletedUserException.java
  src/main/java/com/wooribound/global/exception/WithdrawException.java
  src/main/java/com/wooribound/global/handler/GlobalExceptionHandler.java
  src/main/java/com/wooribound/global/security/DeletedUserFilter.java
  src/main/java/com/wooribound/global/security/JWTFilter.java
  src/main/java/com/wooribound/global/security/SecurityConfig.java
  src/main/java/com/wooribound/global/security/successhandler/WbUserSuccessHandler.java
  src/main/java/com/wooribound/global/security/userdetail/wbuser/WbUserDetailService.java
  src/main/resources/application.properties
Labels: enhancement

#78 [fix] #77 - 개인회원 이력서 조회 URL 수정
  src/main/java/com/wooribound/api/admin/controller/AdminIndividualController.java
  src/main/java/com/wooribound/domain/resume/ResumeServiceImpl.java
Labels: fix

#79 탈퇴한 유저의 로그인 시도 시 410에러 처리
  src/main/java/com/wooribound/global/security/CustomAuthenticationFilter.java
  src/main/java/com/wooribound/global/security/userdetail/enterprise/EnterpriseUserDetailService.java
Labels: enhancement

#80 [fix] #77 - 기업상세 정보 요청 메소드 수정
  src/main/java/com/wooribound/api/admin/controller/AdminEnterpriseController.java
Labels: fix

#81 [feat] #72 - 지혜 나눔/등록 관련 API 추가
  src/main/java/com/wooribound/api/individual/controller/WbUserKnowhowController.java
  src/main/java/com/wooribound/api/individual/facade/WBUserKnowhowFacade.java
  src/main/java/com/wooribound/domain/knowhow/Knowhow.java
  src/main/java/com/wooribound/domain/knowhow/KnowhowRepository.java
  src/main/java/com/wooribound/domain/knowhow/dto/WbUserKnowhowDTO.java
  src/main/java/com/wooribound/domain/knowhow/service/WbUserKnowhowService.java
  src/main/java/com/wooribound/domain/knowhow/service/WbUserKnowhowServiceImpl.java
  src/main/java/com/wooribound/global/exception/KnowhowNotFoundException.java
  src/main/java/com/wooribound/global/exception/UnauthorizedAccessException.java
  src/main/resources/application.properties
Labels: enhancement

#84 [fix] #72 - 지혜나눔 삭제 비지니스 로직 오류 수정
  src/main/java/com/wooribound/domain/knowhow/service/WbUserKnowhowServiceImpl.java
Labels: fix

#82 [fix] #26 - job posting 관련 기능 수정
  src/main/java/com/wooribound/api/corporate/controller/EnterpriseJobPostingController.java
  src/main/java/com/wooribound/api/corporate/facade/EnterpriseJobPostingFacade.java
  src/main/java/com/wooribound/api/individual/controller/WbUserJobPostingController.java
  src/main/java/com/wooribound/api/individual/dto/JobPostingProjection.java
  src/main/java/com/wooribound/api/individual/dto/UserJobPostingDTO.java
  src/main/java/com/wooribound/api/individual/dto/UserJobPostingReqDTO.java
  src/main/java/com/wooribound/api/individual/facade/WbUserJobPostingFacade.java
  src/main/java/com/wooribound/domain/interestjob/InterestJobRepository.java
  src/main/java/com/wooribound/domain/jobposting/JobPosting.java
  src/main/java/com/wooribound/domain/jobposting/JobPostingRepository.java
  src/main/java/com/wooribound/domain/jobposting/Service/AdminJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/jobposting/Service/EntJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/EntJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/jobposting/dto/JobPostingDTO.java
  src/main/java/com/wooribound/domain/jobposting/dto/JobPostingDetailDTO.java
  src/main/java/com/wooribound/domain/jobposting/dto/JobPostingDetailProjection.java
  src/main/java/com/wooribound/domain/wbuser/WbUserRepository.java
  src/main/java/com/wooribound/domain/workhistory/WorkHistoryRepository.java
  src/main/java/com/wooribound/global/constant/PostState.java
  src/main/resources/data.sql
Labels: fix

#83 인증 관련 기능 완료
  src/main/java/com/wooribound/api/corporate/controller/EnterpriseAuthController.java
  src/main/java/com/wooribound/api/corporate/facade/EnterpriseAuthFacade.java
  src/main/java/com/wooribound/domain/enterprise/EnterpriseService.java
  src/main/java/com/wooribound/domain/enterprise/EnterpriseServiceImpl.java
  src/main/java/com/wooribound/global/exception/NotValidPasswordException.java
  src/main/java/com/wooribound/global/handler/GlobalExceptionHandler.java
  src/main/java/com/wooribound/global/security/JWTFilter.java
  src/main/java/com/wooribound/global/security/SecurityConfig.java
  src/main/java/com/wooribound/global/security/controller/AuthController.java
  src/main/java/com/wooribound/global/security/userdetail/enterprise/EnterpriseUserDetailService.java
  src/main/java/com/wooribound/global/util/AuthenticateUtil.java
  src/main/resources/data.sql
Labels: enhancement

#85 [fix] #77 - 기업회원 목록 조회 쿼리문 수정
  src/main/java/com/wooribound/domain/enterprise/EnterpriseRepository.java
Labels: enhancement

#86 [chore] #35 - notification 엔터티에 생성일 컬럼 추가
  src/main/java/com/wooribound/domain/jobposting/Service/AdminJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/notification/Notification.java
  src/main/resources/data.sql
Labels: fix

#87 [feat] #34 -기업 회원 관련 기능 수정 및 구현
  src/main/java/com/wooribound/api/corporate/controller/EnterpriseJobPostingController.java
  src/main/java/com/wooribound/api/corporate/facade/EnterpriseJobPostingFacade.java
  src/main/java/com/wooribound/domain/jobposting/JobPostingRepository.java
  src/main/java/com/wooribound/domain/jobposting/Service/EntJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/EntJobPostingServiceImpl.java
Labels: enhancement

#88 Fix/#77 admin enterprise
  src/main/java/com/wooribound/domain/admin/AdminServiceImpl.java
  src/main/java/com/wooribound/global/exception/NoApproveStatusException.java
  src/main/java/com/wooribound/global/handler/GlobalExceptionHandler.java
Labels: fix

#89 [feat] #33 - 개인회원 정보 직종 추가
  src/main/java/com/wooribound/api/individual/controller/WbUserInfoController.java
  src/main/java/com/wooribound/api/individual/dto/WbUserDTO.java
  src/main/java/com/wooribound/api/individual/facade/WbUserInfoFacade.java
  src/main/java/com/wooribound/domain/interestjob/InterestJob.java
  src/main/java/com/wooribound/domain/wbuser/WbUserService.java
  src/main/java/com/wooribound/domain/wbuser/WbUserServiceImpl.java
  src/main/java/com/wooribound/global/exception/NoWbUserException.java
Labels: enhancement

#90 [update] #68 - 알림 관련 API 수정 및 추가
  src/main/java/com/wooribound/api/individual/controller/WbUserNotificationController.java
  src/main/java/com/wooribound/domain/knowhow/service/WbUserKnowhowServiceImpl.java
  src/main/java/com/wooribound/domain/notification/NotificationRepository.java
  src/main/java/com/wooribound/domain/notification/dto/NotificationDTO.java
  src/main/java/com/wooribound/domain/notification/service/NotificationService.java
  src/main/java/com/wooribound/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/wooribound/global/exception/NotEntityException.java
Labels: duplicate

#91 Fix/#77 admin knowhow
  src/main/java/com/wooribound/api/admin/controller/AdminKnowhowController.java
  src/main/java/com/wooribound/domain/knowhow/Knowhow.java
  src/main/java/com/wooribound/domain/knowhow/KnowhowRepository.java
  src/main/java/com/wooribound/domain/knowhow/dto/AdminKnowhowDetailDTO.java
  src/main/java/com/wooribound/domain/knowhow/dto/AdminKnowhowDetailProjection.java
  src/main/java/com/wooribound/domain/knowhow/service/AdminKnowhowServiceImpl.java
Labels: fix

#92 [fix] #26 - 공고 로그인 Authentication 변경
  src/main/java/com/wooribound/api/individual/controller/WbUserJobPostingController.java
  src/main/java/com/wooribound/api/individual/dto/UserJobPostingReqDTO.java
  src/main/java/com/wooribound/api/individual/facade/WbUserJobPostingFacade.java
  src/main/java/com/wooribound/domain/jobposting/JobPostingRepository.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingServiceImpl.java
Labels: fix

#93 [fix] #77 - 채용공고 목록 조회시, 삭제처리된 건 제외
  src/main/java/com/wooribound/api/individual/controller/WbUserJobPostingController.java
  src/main/java/com/wooribound/domain/jobposting/JobPostingRepository.java
Labels: fix

#94 [fix] #34 - 기업공고조회 관련 기능 수정
  src/main/java/com/wooribound/api/corporate/controller/EnterpriseJobPostingController.java
  src/main/java/com/wooribound/api/corporate/dto/JobPostingReqDTO.java
  src/main/java/com/wooribound/api/corporate/facade/EnterpriseJobPostingFacade.java
  src/main/java/com/wooribound/api/individual/controller/WbUserJobPostingController.java
  src/main/java/com/wooribound/api/individual/dto/JobPostingProjection.java
  src/main/java/com/wooribound/api/individual/facade/WbUserJobPostingFacade.java
  src/main/java/com/wooribound/domain/jobposting/JobPostingRepository.java
  src/main/java/com/wooribound/domain/jobposting/Service/EntJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/EntJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingService.java
  src/main/java/com/wooribound/domain/jobposting/Service/WbUserJobPostingServiceImpl.java
  src/main/java/com/wooribound/global/util/AuthenticateUtil.java
Labels: fix

#95 Chore/#77 admin knowhow
  src/main/java/com/wooribound/api/admin/controller/AdminKnowhowController.java
Labels: fix

#96 [feat] #33 - 이력서 관련 API
  build.gradle
  src/main/java/com/wooribound/api/corporate/controller/EnterpriseJobPostingController.java
  src/main/java/com/wooribound/api/corporate/facade/EnterpriseJobPostingFacade.java
  src/main/java/com/wooribound/api/individual/controller/WbUserResumeController.java
  src/main/java/com/wooribound/domain/knowhow/service/WbUserKnowhowServiceImpl.java
  src/main/java/com/wooribound/domain/resume/Resume.java
  src/main/java/com/wooribound/domain/resume/ResumeRepository.java
  src/main/java/com/wooribound/domain/resume/ResumeService.java
  src/main/java/com/wooribound/domain/resume/ResumeServiceImpl.java
  src/main/java/com/wooribound/domain/resume/dto/ResumeDTO.java
  src/main/java/com/wooribound/global/config/S3Config.java
  src/main/resources/application.properties
Labels: enhancement

#98 Chore/#34 ent info
  src/main/java/com/wooribound/api/corporate/controller/EnterpriseInfoController.java
  src/main/java/com/wooribound/api/corporate/facade/EnterpriseInfoFacade.java
Labels: enhancement, fix

#99 Chore/#35 admin swagger
  src/main/java/com/wooribound/api/admin/controller/AdminAuthController.java
  src/main/java/com/wooribound/api/admin/controller/AdminEnterpriseController.java
  src/main/java/com/wooribound/api/admin/controller/AdminIndividualController.java
  src/main/java/com/wooribound/api/admin/controller/AdminJobPostingController.java
  src/main/java/com/wooribound/api/admin/controller/AdminKnowhowController.java
Labels: enhancement

#100 [update] #97 - 채용 공고 지원 / 취소 / 지원 목록 API 수정
  src/main/java/com/wooribound/api/individual/controller/WbUserInfoController.java
  src/main/java/com/wooribound/api/individual/controller/WbUserJobPostingController.java
  src/main/java/com/wooribound/api/individual/facade/WbUserInfoFacade.java
  src/main/java/com/wooribound/api/individual/facade/WbUserJobPostingFacade.java
  src/main/java/com/wooribound/domain/userapply/Service/UserApplyService.java
  src/main/java/com/wooribound/domain/userapply/Service/UserApplyServiceImpl.java
  src/main/java/com/wooribound/domain/userapply/UserApply.java
  src/main/java/com/wooribound/domain/userapply/UserApplyRepository.java
  src/main/java/com/wooribound/domain/userapply/dto/WbUserApplyDTO.java
Labels: enhancement

#102 [update] #101 - 기업회원 공고 등록 API 수정
  src/main/java/com/wooribound/api/corporate/controller/EnterpriseJobPostingController.java
  src/main/java/com/wooribound/api/corporate/dto/JobPostingReqDTO.java
  src/main/java/com/wooribound/domain/job/JobRepository.java
  src/main/java/com/wooribound/domain/jobposting/JobPosting.java
  src/main/java/com/wooribound/domain/jobposting/JobPostingRepository.java
  src/main/java/com/wooribound/domain/jobposting/Service/EntJobPostingServiceImpl.java
  src/main/java/com/wooribound/domain/resume/ResumeServiceImpl.java
  src/main/java/com/wooribound/global/util/S3Util.java
  src/main/resources/application.properties
Labels: enhancement

#106 [feat] #33 - 개인 회원 직종 수정 추가
  src/main/java/com/wooribound/api/individual/controller/WbUserInfoController.java
  src/main/java/com/wooribound/api/individual/dto/WbUserUpdateDTO.java
  src/main/java/com/wooribound/api/individual/facade/WbUserInfoFacade.java
  src/main/java/com/wooribound/domain/interestjob/InterestJobRepository.java
  src/main/java/com/wooribound/domain/job/JobRepository.java
  src/main/java/com/wooribound/domain/wbuser/WbUserService.java
  src/main/java/com/wooribound/domain/wbuser/WbUserServiceImpl.java
  src/main/java/com/wooribound/domain/workhistory/WorkHistoryRepository.java
Labels: enhancement
